server:
  port: 8081
spring:
  application:
    name: weatherservice

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    com.skycast.weatherservice: DEBUG
